[tool.mypy]
check_untyped_defs = true
disable_error_code = ['misc', 'union-attr', 'has-type', 'import-untyped', 'var-annotated']

[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = ['E9', 'F63', 'F7', 'F82']

[tool.ruff.format]
quote-style = 'single'

